### ISSUE TITLE
unexpected keyword argument 'lyrics' on import

### ISSUE THREAD

**Issue by zane-schaffer** [snejus/beetcamp#22]
running a standard import using this plugin for the first time - shoots this error out for every track

```
bandcamp: Unexpected error obtaining https://vomitforth-maggotstomp.bandcamp.com/album/northeastern-deprivation, please report at https://github.com/snejus/beetcamp/issues/new
Traceback (most recent call last):
  File "/home/dietpi/.local/lib/python3.9/site-packages/beetsplug/bandcamp/__init__.py", line 214, in handle
    return getattr(guru, attr)
  File "/home/dietpi/.local/lib/python3.9/site-packages/beetsplug/bandcamp/_metaguru.py", line 663, in album
    tracks=list(map(get_trackinfo, tracks)),
  File "/home/dietpi/.local/lib/python3.9/site-packages/beetsplug/bandcamp/_metaguru.py", line 618, in _trackinfo
    track_info = TrackInfo(
TypeError: __init__() got an unexpected keyword argument 'lyrics'
```

my config.yaml:

```
import:
    copy: no
    write: no
    link: no
    hardlink: yes
    move: no
plugins: bandcamp
bandcamp:
  search_max: 5
  exclude_extra_fields:
    - lyrics
    - comments
```

any idea how to get past this? makes it incredible annoying to go through tracks as this just spams multiple times for each track

**Comment by snejus** [comment]
hi @zane-schaffer, is your _beets_ version by any chance below **1.5.0**?

**Comment by snejus** [comment]
This should now be fixed in `0.12.0`.
