### ISSUE TITLE
`isodate` and `bs4` modules are required but not documented

### ISSUE THREAD

**Issue by eramdam** [snejus/beetcamp#53]
Maybe something is wrong with my setup but when I first tried installing `beetcamp` and using it with `beets`, I got errors about `bs4` and `isodate` being missing. Could be useful to add those in the README?

```
> beet --version
** error loading plugin bandcamp:
Traceback (most recent call last):
  File "/Users/damien/Library/Application Support/pipx/venvs/beets/lib/python3.12/site-packages/beets/plugins.py", line 268, in load_plugins
    namespace = __import__(modname, None, None)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/damien/.config/beets/plugins/beetsplug/bandcamp.py", line 29, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

beets version 1.6.0
Python version 3.12.1
plugins: chroma, discogs, duplicates, edit, embedart, hook, importadded, inline, lastgenre
~
> pipx inject beets bs4
  injected package bs4 into venv beets
done! ✨ 🌟 ✨
~
>
~
> beet --version
** error loading plugin bandcamp:
Traceback (most recent call last):
  File "/Users/damien/Library/Application Support/pipx/venvs/beets/lib/python3.12/site-packages/beets/plugins.py", line 268, in load_plugins
    namespace = __import__(modname, None, None)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/damien/.config/beets/plugins/beetsplug/bandcamp.py", line 30, in <module>
    import isodate
ModuleNotFoundError: No module named 'isodate'

beets version 1.6.0
Python version 3.12.1
plugins: chroma, discogs, duplicates, edit, embedart, hook, importadded, inline, lastgenre
~
> pipx inject beets isodate
  injected package isodate into venv beets
done! ✨ 🌟 ✨
~
> beet --version
beets version 1.6.0
Python version 3.12.1
plugins: bandcamp, chroma, discogs, duplicates, edit, embedart, hook, importadded, inline, lastgenre
```

**Comment by snejus** [comment]
Hmm something is weird here. Any usage of `bs4` or `isodate` has been removed 3 years ago. Are you sure you're using an up-to-date version of beetcamp?

You can check this with `pip show beetcamp`. You'd want to update it with `pip install -U beetcamp`

**Comment by eramdam** [comment]
Indeed, I must have had something weird in my setup. I re-installed it with regular pip and not pipx and it now installed the newer version. Sorry for the invalid issue 😛
