### ISSUE TITLE
Doesn't seem to be able to fetch from Bandcamp anymore?

### ISSUE THREAD

**Issue by eramdam** [snejus/beetcamp#64]
Example with a given URL:
```
> beetcamp https://carbonbasedlifeforms.bandcamp.com/album/seeker
bandcamp: URL Not found: https://carbonbasedlifeforms.bandcamp.com/album/seeker
bandcamp: URL Not found: https://carbonbasedlifeforms.bandcamp.com/album/seeker
bandcamp: Failed obtaining https://carbonbasedlifeforms.bandcamp.com/album/seeker
bandcamp: URL Not found: https://carbonbasedlifeforms.bandcamp.com/album/seeker
bandcamp: Failed obtaining https://carbonbasedlifeforms.bandcamp.com/album/seeker
Traceback (most recent call last):
  File "/Users/damien/.local/bin/beetcamp", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/damien/Library/Application Support/pipx/venvs/beetcamp/lib/python3.12/site-packages/beetsplug/bandcamp/__init__.py", line 399, in main
    raise AssertionError("Failed to find a release under the given url")
AssertionError: Failed to find a release under the given url
```

Example with an album search:
```
> beetcamp -a "smooth mcgroove"
Traceback (most recent call last):
  File "/Users/damien/.local/bin/beetcamp", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/damien/Library/Application Support/pipx/venvs/beetcamp/lib/python3.12/site-packages/beetsplug/bandcamp/__init__.py", line 379, in main
    search_results = search_bandcamp(**search_vars)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/damien/Library/Application Support/pipx/venvs/beetcamp/lib/python3.12/site-packages/beetsplug/bandcamp/search.py", line 115, in search_bandcamp
    return parse_and_sort_results(get(url), **kwargs)
                                  ^^^^^^^^
  File "/Users/damien/Library/Application Support/pipx/venvs/beetcamp/lib/python3.12/site-packages/beetsplug/bandcamp/search.py", line 99, in get_url
    response.raise_for_status()
  File "/Users/damien/Library/Application Support/pipx/venvs/beetcamp/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://bandcamp.com/search?page=1&q=smooth%20mcgroove&item_type=a
```

- beetcamp 0.19.1 with Python 3.12.4 on macOS 14.5

**Comment by eramdam** [comment]
I tried on a Linux (Debian 12) VM and it seems to work fine with Python 3.11.. I can't easily downgrade to Python 3.11 on macOS so maybe it's related? 😓

**Comment by snejus** [comment]
Thanks for reporting this @eramdam. @ThinkChaos has fixed this issue and the package has now been updated on pypi :)

**Comment by ThinkChaos** [comment]
I hope it fixes it, but there might be other things that trigger 403s for others. Only experience will tell!

**Comment by eramdam** [comment]
Hell yeah, that seems to work, thanks!
